# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'azurepipeline-conn'
    subscriptionId: 'e008dc56-edec-4bd8-aba0-7acae2178224'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'test12345'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'createwebapp/azuredeploy.json'
    overrideParameters: '-projectName test12345p -linkedTemplateUri https://raw.githubusercontent.com/bwczhao/test1234-repo/master/createwebapp/linkedStorageAccount.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'